(lang dune 2.0)
(name oc)

(authors     ["Dmitry Ponyatov <dponyatov@gmail.com>"])
(maintainers  "Dmitry Ponyatov <dponyatov@gmail.com>" )

(license MIT)

(package
 (name oc)
 (synopsis "OCaml-hosted #compilib: Compiler Library")
 (depends ocaml core utop dune ocamlformat))
